<template>
  <b-container fluid>
    <h3>About</h3>
    <pre>AutoDetours allows to trace the syscalls generated by a Windows PE.
  The goal of this project is automatizing and parallalizing the previous step to generate a dataset for exploitation.
  It's a project realized during the last year of our engineering school in collaboration with LSE (EPITA SECURITY'S LABORATORY).
  If you have any questions you can contact us by mail or open an issue/PR on github.
  </pre>
    <br>
    <pre>This project has been developed by:</pre>
    <b-row class="mb-4">
    <ul>
      <li>
        <a href=mailto:baptistin.boilot@epita.fr>Kn0wl3dge</a>
      </li>
      <li>
        <a href=mailto:didier.zanello@epita.fr>Radion</a>
      </li>
      <li>
        <a href=mailto:thomas.castelot@epita.fr>Prolintos</a>
      </li>
      <li>
        <a href=mailto:victoria.krajcovicova@epita.fr>Deacllock</a>
      </li>
    </ul>
    </b-row>
    <pre>Special thanks to Sebdraven who supervised us</pre>
  </b-container>
</template>

<script>
export default {
  name: 'About'
}
</script>

<style scoped>
</style>
