

all:
    @if exist "Detours\src\Makefile" cd "Detours\src" && $(MAKE) /NOLOGO /$(MAKEFLAGS) && cd ..\..
    @if exist "withdll\Makefile" cd "withdll" && $(MAKE) /NOLOGO /$(MAKEFLAGS) && cd ..
    @if exist "traceapi\Makefile" cd "traceapi" && $(MAKE) /NOLOGO /$(MAKEFLAGS) && cd ..