name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    # - name: Set up Vuejs
    #   uses: actions/setup-vuejs@v1
    #   with:
    #     vuesjs-version: 3.0.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        pip install pylint
        npm install vue@next
        npm install eslint --save-dev
    - name: Analysing the code with pylint
      run: |
        find . -type f -name "*.py" | xargs pylint
    - name: Analysing the code with eslint
      run: |
        find . -type f -name "*.vue" | npm eslint
