name: Eslint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yarn add eslint --dev
        npm install @babel/core 
        npm install webpack
        npm install typescript
        npm install eslint-plugin-nuxt@latest --save-dev
        npm install @babel/eslint-parser
        npm install @nuxtjs/eslint-module
        npm install @nuxtjs/eslint-config
    - name: Analysing the code with eslint
      run: |
        sudo npm i -g eslint
        find . -type f -name "*.vue" | xargs eslint
