name: Eslint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        npm install vue@next
        npm install eslint
    - name: Install eslint
      run: |
        npm i -g eslint
    - name: Analysing the code with eslint
      run: |
        find . -type f -name "*.vue" | eslint
