name: Eslint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install eslint
    - name: Install eslint
      run: |
        sudo npm i -g eslint
    - name: Analysing the code with eslint
      run: |
        find . -type f -name "*.vue" | xargs eslint -c "frontend/.eslintrc.js"
